site_name: BotGuardianes
repo_url: https://github.com/tfg-projects-dit-us/BotGuardianes

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]

nav:
  - Principal: index.md
  - telegram_tools: telegram_tools.md
  - servicio_rest: servicio_rest.md
  - gestor_calendario: gestor_calendario.md
  - config: config.md