calendarios:
    url_propuestas: URL
    url_definitivos: URL 
    usuario: usuario
    contrasena: contrasena
telegram:
    token_bot: IDTOKENBOT
log:
    level: warning
REST:
    url_insertartelegramID: URL
    url_getIDporemail: URL
    contrasena: contrasena
    usuario: USUARIO