calendarios:
    url_propuestas: http://40.114.254.128/caldav.php/usuario/calendar/propuestas
    url_definitivos: http://40.114.254.128/caldav.php/usuario/calendar/guardias 
telegram:
    token_bot: IDTOKENBOT
log:
    level: warning